config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('home/', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import landing_page, GetTest

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('test/', GetTest.as_view(), name='test'),
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users_images/', blank=True, null=True, default='default_img/user_img.png')

    class Meta:
        db_table = 'customuser'

    def __str__(self):
        return self.username

users/forms.py
from django import forms

from users.models import CustomUser


class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'password', 'image')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


def landing_page(request):
    return render(request, 'landing_page.html')


class GetTest(LoginRequiredMixin, View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request,'get_test.html')
        else:
            return redirect('users:login')

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import CustomUser


class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
        return render(request, 'register.html', context=context)


class LoginView(View):
    def get(self, request):
        login_form =AuthenticationForm()
        context = {
            'form':login_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect('landing_page')
        return render(request, 'login.html', context={'form': login_form})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('landing_page')



# class RegisterView(View):
#     def get(self, request):
#         return render(request, 'register.html')
#
#     def post(self, request):
#         username = request.POST['username']
#         password = request.POST['password']
#         email = request.POST['email']
#         first_name = request.POST['first_name']
#         last_name = request.POST['last_name']
#
#         user = CustomUser.objects.create_user(
#             username=username,
#             email=email,
#             first_name=first_name,
#             last_name=last_name,
#         )
#         user.set_password(password)
#         return redirect('users:login')

templates/get_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
    <h1>This is test page</h1>
</body>
</html>

templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
    <h1>Home page</h1>
    <a href="{% url 'users:register' %}">Register</a> /
    <a href="{% url 'test' %}">Test</a> /
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
    {% endif%}
</body>
</html>

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
</head>
<body>
    <h1>Login</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form }}

        <button type="submit">Submit</button>
    </form>
</body>
</html>

users/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register page</title>
</head>
<body>
    <h1>Register</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form }}

        <button type="submit">Submit</button>
    </form>

<!--    <form method="POST" action="{% url 'users:register' %}">-->
<!--        {% csrf_token %}-->
<!--        {{ form }}-->

<!--        <label for="username">Username</label>-->
<!--        <input type="text" name="username" id="username"> <br/> <br/>-->

<!--        <label for="first_name">First name</label>-->
<!--        <input type="text" name="first_name" id="first_name"> <br/> <br/>-->

<!--        <label for="last_name">Last name</label>-->
<!--        <input type="text" name="last_name" id="last_name"> <br/> <br/>-->

<!--        <label for="email">Email</label>-->
<!--        <input type="email" name="email" id="email"> <br/> <br/>-->

<!--        <label for="password">Password</label>-->
<!--        <input type="password" name="password" id="password"> <br/> <br/>-->

<!--        <button type="submit">Submit</button>-->

<!--    </form>-->

</body>
</html>